//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.12.0
//     from Assets/Scripts/Player/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Player/PlayerControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""1bc50833-14e3-4bbd-83ce-21e65ae6e47d"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a76041ab-2327-40d3-afa7-d6e34a7136e4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""790936c1-6f5c-42d2-8c00-b44e8e10fd95"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""81705159-2ec3-4c5a-a689-5d857bffa727"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""a875056f-2094-49f9-9597-b1a6d1e72016"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""a86f6ce9-59ff-4857-a91f-f09631cc6cdc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Flashlight"",
                    ""type"": ""Button"",
                    ""id"": ""17b2c494-b2e2-4709-9e70-2a8779bb697e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""f55fb44b-74f9-46e0-b5fc-5a67c1bbc524"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""c42d47bd-a890-4e8b-8335-e87033a59424"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CheckFOV"",
                    ""type"": ""Button"",
                    ""id"": ""469c2d50-bb1a-4504-9ae3-3bcdf700eb5a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""65956143-cd5d-4b2f-a13c-3574d3b79bd0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b5107d9f-bcbb-4e4d-aaa8-fa879322db72"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5fc35cde-e2cc-43fe-b2fd-27e0ea57a262"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""db3c8d0b-ad27-4aa0-ab30-0aac3b74b638"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ff90128a-0c6d-4afb-9176-073d959875cb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0cd4c33e-ee81-4708-83ae-300055a3ca86"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""898c412a-208d-4f7d-bded-0e96d7893783"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b43db9b-be35-47ce-ae83-0b61d66455f1"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""427958eb-1a56-4008-b1e9-0dd80dd6758f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""793a9db4-c2eb-4293-b546-794edbd701c3"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flashlight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94f39cf4-c420-4176-a5c8-8e08b755b5c9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b23c09ef-7edc-47ce-92af-ed57635d7d95"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2a7b182-c497-4800-b6b5-08fb7c441bc3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CheckFOV"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InventoryUI"",
            ""id"": ""5bf7cd22-1822-456b-80d8-c71514285d90"",
            ""actions"": [
                {
                    ""name"": ""InventoryExit"",
                    ""type"": ""Button"",
                    ""id"": ""e1a50dc3-c0c4-471a-80df-a697d720097a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropItem"",
                    ""type"": ""Button"",
                    ""id"": ""41f7f037-635c-44c8-ac22-e7a09d1054e6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollUp"",
                    ""type"": ""Button"",
                    ""id"": ""c1a06c59-ab14-4e36-8b1d-6d51b48c79e8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollDown"",
                    ""type"": ""Button"",
                    ""id"": ""3671ea06-1282-46bb-b684-60e8847aabbd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""741149cc-c6c7-418e-a88d-4bfdd4b64f31"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebf7f75d-6352-430f-8d4f-bfba56482dfd"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60804a96-331c-4cb7-99ca-4dedb70c3caf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec3bbfb5-3c80-4dbb-90be-e8d1c8929aca"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""HackUI"",
            ""id"": ""736556b2-554a-4cf3-800f-24bdae5bd588"",
            ""actions"": [
                {
                    ""name"": ""HackExit"",
                    ""type"": ""Button"",
                    ""id"": ""3e252e98-45ac-49e7-80f6-fd357e484c1a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HackInteract"",
                    ""type"": ""Button"",
                    ""id"": ""2c5869a4-528e-41bb-b7ec-828fd07ebb37"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""04100be9-e87c-4633-b845-770bb94910d9"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HackExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72a31675-5a69-4ca9-8b02-05aae8973625"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HackInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ChestUI"",
            ""id"": ""5c1570f2-ff87-4c4f-99af-ef6f7bde8447"",
            ""actions"": [
                {
                    ""name"": ""ChestExit"",
                    ""type"": ""Button"",
                    ""id"": ""9e8e878e-5992-466a-bad0-10d71b984250"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TransferItem"",
                    ""type"": ""Button"",
                    ""id"": ""d50694c9-e9fc-4cec-9bdc-4ebd93bd8900"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollUpInventory"",
                    ""type"": ""Button"",
                    ""id"": ""b85c4790-fd0f-43f7-9f15-316a14658864"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollDownInventory"",
                    ""type"": ""Button"",
                    ""id"": ""e1471963-07de-47b6-8994-8a57f871afca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollUpChest"",
                    ""type"": ""Button"",
                    ""id"": ""36759108-c9e1-4efe-bfc9-e03258d8766f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollDownChest"",
                    ""type"": ""Button"",
                    ""id"": ""e71b98e1-4a8b-4281-abf3-7e36cbe3d8ce"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9272dfae-292e-4c32-be78-1474edeb824a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChestExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f08cda50-6137-4259-9af1-8fca9e948385"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TransferItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85ac98c1-e237-49ba-9b16-44e981a24b10"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollUpInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""960842ab-ac49-491e-aaf7-5b9cf0b35c1f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollDownInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""914f199f-1de6-459b-aea8-861bd753d39a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollUpChest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d49f4cc-f3e8-418c-9a40-be89af4c7f28"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollDownChest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SpaceshipPanelUI"",
            ""id"": ""fe9e0d5a-1e6f-463d-b7fa-2dec2dcc0c05"",
            ""actions"": [
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""de8d6c6a-3d45-48c3-9569-a226aa75e832"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ComplexList"",
                    ""type"": ""Button"",
                    ""id"": ""94a4680c-0907-4607-b945-0635af03e875"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectComplex"",
                    ""type"": ""Button"",
                    ""id"": ""71112f23-37f2-4697-af55-3523cf7dafe2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""c74b84f8-a832-40a8-ba47-efb0b91ae9de"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationUp"",
                    ""type"": ""Button"",
                    ""id"": ""783d3c1e-8edd-4eb2-9036-37bdeed65da2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationDown"",
                    ""type"": ""Button"",
                    ""id"": ""b80f4c2a-12f9-443b-ae13-da643f113676"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0b05410c-b9f6-4ddd-b484-843343fc0cca"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7163288b-f813-41ac-b03a-6abffca59db7"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ComplexList"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82df4210-72a2-4f89-874d-a676e8e3d5e1"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectComplex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2780fcc7-4867-451a-9280-dfed17193c95"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9adadaf1-3bb3-4164-8589-48be53a5779b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigationUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c195506-f24e-4aa2-bb7e-16dbac8068a7"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigationDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
        m_Gameplay_Crouch = m_Gameplay.FindAction("Crouch", throwIfNotFound: true);
        m_Gameplay_Sprint = m_Gameplay.FindAction("Sprint", throwIfNotFound: true);
        m_Gameplay_Look = m_Gameplay.FindAction("Look", throwIfNotFound: true);
        m_Gameplay_Jump = m_Gameplay.FindAction("Jump", throwIfNotFound: true);
        m_Gameplay_Flashlight = m_Gameplay.FindAction("Flashlight", throwIfNotFound: true);
        m_Gameplay_Interact = m_Gameplay.FindAction("Interact", throwIfNotFound: true);
        m_Gameplay_Inventory = m_Gameplay.FindAction("Inventory", throwIfNotFound: true);
        m_Gameplay_CheckFOV = m_Gameplay.FindAction("CheckFOV", throwIfNotFound: true);
        // InventoryUI
        m_InventoryUI = asset.FindActionMap("InventoryUI", throwIfNotFound: true);
        m_InventoryUI_InventoryExit = m_InventoryUI.FindAction("InventoryExit", throwIfNotFound: true);
        m_InventoryUI_DropItem = m_InventoryUI.FindAction("DropItem", throwIfNotFound: true);
        m_InventoryUI_ScrollUp = m_InventoryUI.FindAction("ScrollUp", throwIfNotFound: true);
        m_InventoryUI_ScrollDown = m_InventoryUI.FindAction("ScrollDown", throwIfNotFound: true);
        // HackUI
        m_HackUI = asset.FindActionMap("HackUI", throwIfNotFound: true);
        m_HackUI_HackExit = m_HackUI.FindAction("HackExit", throwIfNotFound: true);
        m_HackUI_HackInteract = m_HackUI.FindAction("HackInteract", throwIfNotFound: true);
        // ChestUI
        m_ChestUI = asset.FindActionMap("ChestUI", throwIfNotFound: true);
        m_ChestUI_ChestExit = m_ChestUI.FindAction("ChestExit", throwIfNotFound: true);
        m_ChestUI_TransferItem = m_ChestUI.FindAction("TransferItem", throwIfNotFound: true);
        m_ChestUI_ScrollUpInventory = m_ChestUI.FindAction("ScrollUpInventory", throwIfNotFound: true);
        m_ChestUI_ScrollDownInventory = m_ChestUI.FindAction("ScrollDownInventory", throwIfNotFound: true);
        m_ChestUI_ScrollUpChest = m_ChestUI.FindAction("ScrollUpChest", throwIfNotFound: true);
        m_ChestUI_ScrollDownChest = m_ChestUI.FindAction("ScrollDownChest", throwIfNotFound: true);
        // SpaceshipPanelUI
        m_SpaceshipPanelUI = asset.FindActionMap("SpaceshipPanelUI", throwIfNotFound: true);
        m_SpaceshipPanelUI_Exit = m_SpaceshipPanelUI.FindAction("Exit", throwIfNotFound: true);
        m_SpaceshipPanelUI_ComplexList = m_SpaceshipPanelUI.FindAction("ComplexList", throwIfNotFound: true);
        m_SpaceshipPanelUI_SelectComplex = m_SpaceshipPanelUI.FindAction("SelectComplex", throwIfNotFound: true);
        m_SpaceshipPanelUI_Back = m_SpaceshipPanelUI.FindAction("Back", throwIfNotFound: true);
        m_SpaceshipPanelUI_NavigationUp = m_SpaceshipPanelUI.FindAction("NavigationUp", throwIfNotFound: true);
        m_SpaceshipPanelUI_NavigationDown = m_SpaceshipPanelUI.FindAction("NavigationDown", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, PlayerControls.Gameplay.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_InventoryUI.enabled, "This will cause a leak and performance issues, PlayerControls.InventoryUI.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_HackUI.enabled, "This will cause a leak and performance issues, PlayerControls.HackUI.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_ChestUI.enabled, "This will cause a leak and performance issues, PlayerControls.ChestUI.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_SpaceshipPanelUI.enabled, "This will cause a leak and performance issues, PlayerControls.SpaceshipPanelUI.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Move;
    private readonly InputAction m_Gameplay_Crouch;
    private readonly InputAction m_Gameplay_Sprint;
    private readonly InputAction m_Gameplay_Look;
    private readonly InputAction m_Gameplay_Jump;
    private readonly InputAction m_Gameplay_Flashlight;
    private readonly InputAction m_Gameplay_Interact;
    private readonly InputAction m_Gameplay_Inventory;
    private readonly InputAction m_Gameplay_CheckFOV;
    /// <summary>
    /// Provides access to input actions defined in input action map "Gameplay".
    /// </summary>
    public struct GameplayActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GameplayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Gameplay_Move;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Crouch".
        /// </summary>
        public InputAction @Crouch => m_Wrapper.m_Gameplay_Crouch;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Sprint".
        /// </summary>
        public InputAction @Sprint => m_Wrapper.m_Gameplay_Sprint;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Look".
        /// </summary>
        public InputAction @Look => m_Wrapper.m_Gameplay_Look;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Jump".
        /// </summary>
        public InputAction @Jump => m_Wrapper.m_Gameplay_Jump;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Flashlight".
        /// </summary>
        public InputAction @Flashlight => m_Wrapper.m_Gameplay_Flashlight;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Interact".
        /// </summary>
        public InputAction @Interact => m_Wrapper.m_Gameplay_Interact;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Inventory".
        /// </summary>
        public InputAction @Inventory => m_Wrapper.m_Gameplay_Inventory;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/CheckFOV".
        /// </summary>
        public InputAction @CheckFOV => m_Wrapper.m_Gameplay_CheckFOV;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GameplayActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Flashlight.started += instance.OnFlashlight;
            @Flashlight.performed += instance.OnFlashlight;
            @Flashlight.canceled += instance.OnFlashlight;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Inventory.started += instance.OnInventory;
            @Inventory.performed += instance.OnInventory;
            @Inventory.canceled += instance.OnInventory;
            @CheckFOV.started += instance.OnCheckFOV;
            @CheckFOV.performed += instance.OnCheckFOV;
            @CheckFOV.canceled += instance.OnCheckFOV;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Flashlight.started -= instance.OnFlashlight;
            @Flashlight.performed -= instance.OnFlashlight;
            @Flashlight.canceled -= instance.OnFlashlight;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Inventory.started -= instance.OnInventory;
            @Inventory.performed -= instance.OnInventory;
            @Inventory.canceled -= instance.OnInventory;
            @CheckFOV.started -= instance.OnCheckFOV;
            @CheckFOV.performed -= instance.OnCheckFOV;
            @CheckFOV.canceled -= instance.OnCheckFOV;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />.
        /// </summary>
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GameplayActions" /> instance referencing this action map.
    /// </summary>
    public GameplayActions @Gameplay => new GameplayActions(this);

    // InventoryUI
    private readonly InputActionMap m_InventoryUI;
    private List<IInventoryUIActions> m_InventoryUIActionsCallbackInterfaces = new List<IInventoryUIActions>();
    private readonly InputAction m_InventoryUI_InventoryExit;
    private readonly InputAction m_InventoryUI_DropItem;
    private readonly InputAction m_InventoryUI_ScrollUp;
    private readonly InputAction m_InventoryUI_ScrollDown;
    /// <summary>
    /// Provides access to input actions defined in input action map "InventoryUI".
    /// </summary>
    public struct InventoryUIActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public InventoryUIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "InventoryUI/InventoryExit".
        /// </summary>
        public InputAction @InventoryExit => m_Wrapper.m_InventoryUI_InventoryExit;
        /// <summary>
        /// Provides access to the underlying input action "InventoryUI/DropItem".
        /// </summary>
        public InputAction @DropItem => m_Wrapper.m_InventoryUI_DropItem;
        /// <summary>
        /// Provides access to the underlying input action "InventoryUI/ScrollUp".
        /// </summary>
        public InputAction @ScrollUp => m_Wrapper.m_InventoryUI_ScrollUp;
        /// <summary>
        /// Provides access to the underlying input action "InventoryUI/ScrollDown".
        /// </summary>
        public InputAction @ScrollDown => m_Wrapper.m_InventoryUI_ScrollDown;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_InventoryUI; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="InventoryUIActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(InventoryUIActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="InventoryUIActions" />
        public void AddCallbacks(IInventoryUIActions instance)
        {
            if (instance == null || m_Wrapper.m_InventoryUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InventoryUIActionsCallbackInterfaces.Add(instance);
            @InventoryExit.started += instance.OnInventoryExit;
            @InventoryExit.performed += instance.OnInventoryExit;
            @InventoryExit.canceled += instance.OnInventoryExit;
            @DropItem.started += instance.OnDropItem;
            @DropItem.performed += instance.OnDropItem;
            @DropItem.canceled += instance.OnDropItem;
            @ScrollUp.started += instance.OnScrollUp;
            @ScrollUp.performed += instance.OnScrollUp;
            @ScrollUp.canceled += instance.OnScrollUp;
            @ScrollDown.started += instance.OnScrollDown;
            @ScrollDown.performed += instance.OnScrollDown;
            @ScrollDown.canceled += instance.OnScrollDown;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="InventoryUIActions" />
        private void UnregisterCallbacks(IInventoryUIActions instance)
        {
            @InventoryExit.started -= instance.OnInventoryExit;
            @InventoryExit.performed -= instance.OnInventoryExit;
            @InventoryExit.canceled -= instance.OnInventoryExit;
            @DropItem.started -= instance.OnDropItem;
            @DropItem.performed -= instance.OnDropItem;
            @DropItem.canceled -= instance.OnDropItem;
            @ScrollUp.started -= instance.OnScrollUp;
            @ScrollUp.performed -= instance.OnScrollUp;
            @ScrollUp.canceled -= instance.OnScrollUp;
            @ScrollDown.started -= instance.OnScrollDown;
            @ScrollDown.performed -= instance.OnScrollDown;
            @ScrollDown.canceled -= instance.OnScrollDown;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="InventoryUIActions.UnregisterCallbacks(IInventoryUIActions)" />.
        /// </summary>
        /// <seealso cref="InventoryUIActions.UnregisterCallbacks(IInventoryUIActions)" />
        public void RemoveCallbacks(IInventoryUIActions instance)
        {
            if (m_Wrapper.m_InventoryUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="InventoryUIActions.AddCallbacks(IInventoryUIActions)" />
        /// <seealso cref="InventoryUIActions.RemoveCallbacks(IInventoryUIActions)" />
        /// <seealso cref="InventoryUIActions.UnregisterCallbacks(IInventoryUIActions)" />
        public void SetCallbacks(IInventoryUIActions instance)
        {
            foreach (var item in m_Wrapper.m_InventoryUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InventoryUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="InventoryUIActions" /> instance referencing this action map.
    /// </summary>
    public InventoryUIActions @InventoryUI => new InventoryUIActions(this);

    // HackUI
    private readonly InputActionMap m_HackUI;
    private List<IHackUIActions> m_HackUIActionsCallbackInterfaces = new List<IHackUIActions>();
    private readonly InputAction m_HackUI_HackExit;
    private readonly InputAction m_HackUI_HackInteract;
    /// <summary>
    /// Provides access to input actions defined in input action map "HackUI".
    /// </summary>
    public struct HackUIActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public HackUIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "HackUI/HackExit".
        /// </summary>
        public InputAction @HackExit => m_Wrapper.m_HackUI_HackExit;
        /// <summary>
        /// Provides access to the underlying input action "HackUI/HackInteract".
        /// </summary>
        public InputAction @HackInteract => m_Wrapper.m_HackUI_HackInteract;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_HackUI; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="HackUIActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(HackUIActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="HackUIActions" />
        public void AddCallbacks(IHackUIActions instance)
        {
            if (instance == null || m_Wrapper.m_HackUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HackUIActionsCallbackInterfaces.Add(instance);
            @HackExit.started += instance.OnHackExit;
            @HackExit.performed += instance.OnHackExit;
            @HackExit.canceled += instance.OnHackExit;
            @HackInteract.started += instance.OnHackInteract;
            @HackInteract.performed += instance.OnHackInteract;
            @HackInteract.canceled += instance.OnHackInteract;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="HackUIActions" />
        private void UnregisterCallbacks(IHackUIActions instance)
        {
            @HackExit.started -= instance.OnHackExit;
            @HackExit.performed -= instance.OnHackExit;
            @HackExit.canceled -= instance.OnHackExit;
            @HackInteract.started -= instance.OnHackInteract;
            @HackInteract.performed -= instance.OnHackInteract;
            @HackInteract.canceled -= instance.OnHackInteract;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="HackUIActions.UnregisterCallbacks(IHackUIActions)" />.
        /// </summary>
        /// <seealso cref="HackUIActions.UnregisterCallbacks(IHackUIActions)" />
        public void RemoveCallbacks(IHackUIActions instance)
        {
            if (m_Wrapper.m_HackUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="HackUIActions.AddCallbacks(IHackUIActions)" />
        /// <seealso cref="HackUIActions.RemoveCallbacks(IHackUIActions)" />
        /// <seealso cref="HackUIActions.UnregisterCallbacks(IHackUIActions)" />
        public void SetCallbacks(IHackUIActions instance)
        {
            foreach (var item in m_Wrapper.m_HackUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HackUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="HackUIActions" /> instance referencing this action map.
    /// </summary>
    public HackUIActions @HackUI => new HackUIActions(this);

    // ChestUI
    private readonly InputActionMap m_ChestUI;
    private List<IChestUIActions> m_ChestUIActionsCallbackInterfaces = new List<IChestUIActions>();
    private readonly InputAction m_ChestUI_ChestExit;
    private readonly InputAction m_ChestUI_TransferItem;
    private readonly InputAction m_ChestUI_ScrollUpInventory;
    private readonly InputAction m_ChestUI_ScrollDownInventory;
    private readonly InputAction m_ChestUI_ScrollUpChest;
    private readonly InputAction m_ChestUI_ScrollDownChest;
    /// <summary>
    /// Provides access to input actions defined in input action map "ChestUI".
    /// </summary>
    public struct ChestUIActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ChestUIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ChestUI/ChestExit".
        /// </summary>
        public InputAction @ChestExit => m_Wrapper.m_ChestUI_ChestExit;
        /// <summary>
        /// Provides access to the underlying input action "ChestUI/TransferItem".
        /// </summary>
        public InputAction @TransferItem => m_Wrapper.m_ChestUI_TransferItem;
        /// <summary>
        /// Provides access to the underlying input action "ChestUI/ScrollUpInventory".
        /// </summary>
        public InputAction @ScrollUpInventory => m_Wrapper.m_ChestUI_ScrollUpInventory;
        /// <summary>
        /// Provides access to the underlying input action "ChestUI/ScrollDownInventory".
        /// </summary>
        public InputAction @ScrollDownInventory => m_Wrapper.m_ChestUI_ScrollDownInventory;
        /// <summary>
        /// Provides access to the underlying input action "ChestUI/ScrollUpChest".
        /// </summary>
        public InputAction @ScrollUpChest => m_Wrapper.m_ChestUI_ScrollUpChest;
        /// <summary>
        /// Provides access to the underlying input action "ChestUI/ScrollDownChest".
        /// </summary>
        public InputAction @ScrollDownChest => m_Wrapper.m_ChestUI_ScrollDownChest;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ChestUI; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ChestUIActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ChestUIActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ChestUIActions" />
        public void AddCallbacks(IChestUIActions instance)
        {
            if (instance == null || m_Wrapper.m_ChestUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ChestUIActionsCallbackInterfaces.Add(instance);
            @ChestExit.started += instance.OnChestExit;
            @ChestExit.performed += instance.OnChestExit;
            @ChestExit.canceled += instance.OnChestExit;
            @TransferItem.started += instance.OnTransferItem;
            @TransferItem.performed += instance.OnTransferItem;
            @TransferItem.canceled += instance.OnTransferItem;
            @ScrollUpInventory.started += instance.OnScrollUpInventory;
            @ScrollUpInventory.performed += instance.OnScrollUpInventory;
            @ScrollUpInventory.canceled += instance.OnScrollUpInventory;
            @ScrollDownInventory.started += instance.OnScrollDownInventory;
            @ScrollDownInventory.performed += instance.OnScrollDownInventory;
            @ScrollDownInventory.canceled += instance.OnScrollDownInventory;
            @ScrollUpChest.started += instance.OnScrollUpChest;
            @ScrollUpChest.performed += instance.OnScrollUpChest;
            @ScrollUpChest.canceled += instance.OnScrollUpChest;
            @ScrollDownChest.started += instance.OnScrollDownChest;
            @ScrollDownChest.performed += instance.OnScrollDownChest;
            @ScrollDownChest.canceled += instance.OnScrollDownChest;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ChestUIActions" />
        private void UnregisterCallbacks(IChestUIActions instance)
        {
            @ChestExit.started -= instance.OnChestExit;
            @ChestExit.performed -= instance.OnChestExit;
            @ChestExit.canceled -= instance.OnChestExit;
            @TransferItem.started -= instance.OnTransferItem;
            @TransferItem.performed -= instance.OnTransferItem;
            @TransferItem.canceled -= instance.OnTransferItem;
            @ScrollUpInventory.started -= instance.OnScrollUpInventory;
            @ScrollUpInventory.performed -= instance.OnScrollUpInventory;
            @ScrollUpInventory.canceled -= instance.OnScrollUpInventory;
            @ScrollDownInventory.started -= instance.OnScrollDownInventory;
            @ScrollDownInventory.performed -= instance.OnScrollDownInventory;
            @ScrollDownInventory.canceled -= instance.OnScrollDownInventory;
            @ScrollUpChest.started -= instance.OnScrollUpChest;
            @ScrollUpChest.performed -= instance.OnScrollUpChest;
            @ScrollUpChest.canceled -= instance.OnScrollUpChest;
            @ScrollDownChest.started -= instance.OnScrollDownChest;
            @ScrollDownChest.performed -= instance.OnScrollDownChest;
            @ScrollDownChest.canceled -= instance.OnScrollDownChest;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ChestUIActions.UnregisterCallbacks(IChestUIActions)" />.
        /// </summary>
        /// <seealso cref="ChestUIActions.UnregisterCallbacks(IChestUIActions)" />
        public void RemoveCallbacks(IChestUIActions instance)
        {
            if (m_Wrapper.m_ChestUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ChestUIActions.AddCallbacks(IChestUIActions)" />
        /// <seealso cref="ChestUIActions.RemoveCallbacks(IChestUIActions)" />
        /// <seealso cref="ChestUIActions.UnregisterCallbacks(IChestUIActions)" />
        public void SetCallbacks(IChestUIActions instance)
        {
            foreach (var item in m_Wrapper.m_ChestUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ChestUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ChestUIActions" /> instance referencing this action map.
    /// </summary>
    public ChestUIActions @ChestUI => new ChestUIActions(this);

    // SpaceshipPanelUI
    private readonly InputActionMap m_SpaceshipPanelUI;
    private List<ISpaceshipPanelUIActions> m_SpaceshipPanelUIActionsCallbackInterfaces = new List<ISpaceshipPanelUIActions>();
    private readonly InputAction m_SpaceshipPanelUI_Exit;
    private readonly InputAction m_SpaceshipPanelUI_ComplexList;
    private readonly InputAction m_SpaceshipPanelUI_SelectComplex;
    private readonly InputAction m_SpaceshipPanelUI_Back;
    private readonly InputAction m_SpaceshipPanelUI_NavigationUp;
    private readonly InputAction m_SpaceshipPanelUI_NavigationDown;
    /// <summary>
    /// Provides access to input actions defined in input action map "SpaceshipPanelUI".
    /// </summary>
    public struct SpaceshipPanelUIActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public SpaceshipPanelUIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "SpaceshipPanelUI/Exit".
        /// </summary>
        public InputAction @Exit => m_Wrapper.m_SpaceshipPanelUI_Exit;
        /// <summary>
        /// Provides access to the underlying input action "SpaceshipPanelUI/ComplexList".
        /// </summary>
        public InputAction @ComplexList => m_Wrapper.m_SpaceshipPanelUI_ComplexList;
        /// <summary>
        /// Provides access to the underlying input action "SpaceshipPanelUI/SelectComplex".
        /// </summary>
        public InputAction @SelectComplex => m_Wrapper.m_SpaceshipPanelUI_SelectComplex;
        /// <summary>
        /// Provides access to the underlying input action "SpaceshipPanelUI/Back".
        /// </summary>
        public InputAction @Back => m_Wrapper.m_SpaceshipPanelUI_Back;
        /// <summary>
        /// Provides access to the underlying input action "SpaceshipPanelUI/NavigationUp".
        /// </summary>
        public InputAction @NavigationUp => m_Wrapper.m_SpaceshipPanelUI_NavigationUp;
        /// <summary>
        /// Provides access to the underlying input action "SpaceshipPanelUI/NavigationDown".
        /// </summary>
        public InputAction @NavigationDown => m_Wrapper.m_SpaceshipPanelUI_NavigationDown;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_SpaceshipPanelUI; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="SpaceshipPanelUIActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(SpaceshipPanelUIActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="SpaceshipPanelUIActions" />
        public void AddCallbacks(ISpaceshipPanelUIActions instance)
        {
            if (instance == null || m_Wrapper.m_SpaceshipPanelUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SpaceshipPanelUIActionsCallbackInterfaces.Add(instance);
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
            @ComplexList.started += instance.OnComplexList;
            @ComplexList.performed += instance.OnComplexList;
            @ComplexList.canceled += instance.OnComplexList;
            @SelectComplex.started += instance.OnSelectComplex;
            @SelectComplex.performed += instance.OnSelectComplex;
            @SelectComplex.canceled += instance.OnSelectComplex;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
            @NavigationUp.started += instance.OnNavigationUp;
            @NavigationUp.performed += instance.OnNavigationUp;
            @NavigationUp.canceled += instance.OnNavigationUp;
            @NavigationDown.started += instance.OnNavigationDown;
            @NavigationDown.performed += instance.OnNavigationDown;
            @NavigationDown.canceled += instance.OnNavigationDown;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="SpaceshipPanelUIActions" />
        private void UnregisterCallbacks(ISpaceshipPanelUIActions instance)
        {
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
            @ComplexList.started -= instance.OnComplexList;
            @ComplexList.performed -= instance.OnComplexList;
            @ComplexList.canceled -= instance.OnComplexList;
            @SelectComplex.started -= instance.OnSelectComplex;
            @SelectComplex.performed -= instance.OnSelectComplex;
            @SelectComplex.canceled -= instance.OnSelectComplex;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
            @NavigationUp.started -= instance.OnNavigationUp;
            @NavigationUp.performed -= instance.OnNavigationUp;
            @NavigationUp.canceled -= instance.OnNavigationUp;
            @NavigationDown.started -= instance.OnNavigationDown;
            @NavigationDown.performed -= instance.OnNavigationDown;
            @NavigationDown.canceled -= instance.OnNavigationDown;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SpaceshipPanelUIActions.UnregisterCallbacks(ISpaceshipPanelUIActions)" />.
        /// </summary>
        /// <seealso cref="SpaceshipPanelUIActions.UnregisterCallbacks(ISpaceshipPanelUIActions)" />
        public void RemoveCallbacks(ISpaceshipPanelUIActions instance)
        {
            if (m_Wrapper.m_SpaceshipPanelUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="SpaceshipPanelUIActions.AddCallbacks(ISpaceshipPanelUIActions)" />
        /// <seealso cref="SpaceshipPanelUIActions.RemoveCallbacks(ISpaceshipPanelUIActions)" />
        /// <seealso cref="SpaceshipPanelUIActions.UnregisterCallbacks(ISpaceshipPanelUIActions)" />
        public void SetCallbacks(ISpaceshipPanelUIActions instance)
        {
            foreach (var item in m_Wrapper.m_SpaceshipPanelUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SpaceshipPanelUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="SpaceshipPanelUIActions" /> instance referencing this action map.
    /// </summary>
    public SpaceshipPanelUIActions @SpaceshipPanelUI => new SpaceshipPanelUIActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Gameplay" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
    /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
    public interface IGameplayActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Crouch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCrouch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Sprint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSprint(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLook(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Flashlight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFlashlight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Interact" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnInteract(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Inventory" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnInventory(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CheckFOV" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCheckFOV(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "InventoryUI" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="InventoryUIActions.AddCallbacks(IInventoryUIActions)" />
    /// <seealso cref="InventoryUIActions.RemoveCallbacks(IInventoryUIActions)" />
    public interface IInventoryUIActions
    {
        /// <summary>
        /// Method invoked when associated input action "InventoryExit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnInventoryExit(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DropItem" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDropItem(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ScrollUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnScrollUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ScrollDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnScrollDown(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "HackUI" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="HackUIActions.AddCallbacks(IHackUIActions)" />
    /// <seealso cref="HackUIActions.RemoveCallbacks(IHackUIActions)" />
    public interface IHackUIActions
    {
        /// <summary>
        /// Method invoked when associated input action "HackExit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHackExit(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "HackInteract" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHackInteract(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ChestUI" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ChestUIActions.AddCallbacks(IChestUIActions)" />
    /// <seealso cref="ChestUIActions.RemoveCallbacks(IChestUIActions)" />
    public interface IChestUIActions
    {
        /// <summary>
        /// Method invoked when associated input action "ChestExit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChestExit(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TransferItem" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTransferItem(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ScrollUpInventory" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnScrollUpInventory(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ScrollDownInventory" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnScrollDownInventory(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ScrollUpChest" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnScrollUpChest(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ScrollDownChest" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnScrollDownChest(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "SpaceshipPanelUI" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="SpaceshipPanelUIActions.AddCallbacks(ISpaceshipPanelUIActions)" />
    /// <seealso cref="SpaceshipPanelUIActions.RemoveCallbacks(ISpaceshipPanelUIActions)" />
    public interface ISpaceshipPanelUIActions
    {
        /// <summary>
        /// Method invoked when associated input action "Exit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnExit(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ComplexList" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnComplexList(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectComplex" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectComplex(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Back" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBack(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NavigationUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNavigationUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NavigationDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNavigationDown(InputAction.CallbackContext context);
    }
}
